version: "3.8"
services:
  # api:
  #   container_name: interview-api
  #   image: "interview-api"
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "5050:8080"
  #   networks:
  #     - api-network
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: 200M
  #   labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.interview-api.entrypoints=http"
  #    - "traefik.http.routers.interview-api.rule=Host(`interview-api.srv-desa.nfg-tech.com`)"
  #    - "traefik.http.middlewares.interview-api-https-redirect.redirectscheme.scheme=https"
  #    - "traefik.http.routers.interview-api.middlewares=interview-api-https-redirect"
  #    - "traefik.http.routers.interview-api-secure.entrypoints=https"
  #    - "traefik.http.routers.interview-api-secure.rule=Host(`interview-api.srv-desa.nfg-tech.com`)"
  #    - "traefik.http.routers.interview-api-secure.tls=true"
  #    - "traefik.http.routers.interview-api-secure.service=interview-api"
  #    - "traefik.http.services.interview-api.loadbalancer.server.port=80"
  #    - "traefik.docker.network=proxy"
  db:
    container_name: db-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - db-data:/mnt/sqlserver
    networks:
      - api-network

networks:
  api-network:
    external: true
volumes:
  db-data:
